version: '3.9'
services:
  backend:
    build: .
    ports:
      - 8080:8080
    volumes:
      - ".:/app"
    depends_on:
      - db
      - redis
  db:
    image: postgres:14.1
    restart: always
    environment:
      POSTGRES_DB: ambassador
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_ROOT_PASSWORD: root
    volumes:
      - ".dbdata:/var/postgresql/data"
    ports:
      - 5432:5432

  redis:
    image: redis:latest
    ports:
      - 6379:6379